name: Grosso Antonio
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "readme.md"]

nav:
    - title: "Home"
      url: index.html
    - title: "Azienda"
      url: azienda.html
    - title: "Cilindri Fotoincisi"
      url: cilindri-fotoincisi.html
    - title: "Catalogo Cilindri"
      url: catalogo-cilindri.html
    - title: "Carta Smeriglio"
      url: carta-smeriglio.html
    - title: "Prodotti"
      url: javascript:void(0)
      sub-nav:
          - title: Gomme
            url: gomme.html
          - title: Feltri
            url: feltri.html
          - title: Manicotto per tamponatrici
            url: manicotto-tamponatrici.html
          - title: Tappeto per Dinavac
            url: tappeto-dinavac.html
          - title: Pedana di sollevamento
            url: pedane-di-sollevamento.html
    - title: Pezzi di ricambio
      url: pezzi-di-ricambio.html
    - title: Nuovo
      url: nuovo.html
    - title: Usato
      url: usato.html
    - title: Contatti
      url: contatti.html
