name: Grosso Antonio
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "readme.md"]

nav:
    - title: "Home"
      url: index.html
    - title: "Azienda"
      url: /azienda.html
    - title: "Cilindri Fotoincisi"
      url: /cilindri-fotoincisi.html
    - title: "Catalogo Cilindri"
      url: /catalogo-cilindri.html
    - title: "Carta Smeriglio"
      url: /carta-smeriglio.html
    - title: "Prodotti"
      url: javascript:void(0)
      sub-nav:
          - title: Gomme
            url: /gomme.html
          - title: Feltri
            url: /feltri.html
          - title: Manicotto per tamponatrici
            url: /manicotto-tamponatrici.html
          - title: Tappeto per Dinavac
            url: /tappeto-dinavac.html
          - title: Pedana di sollevamento
            url: /pedane-di-sollevamento.html
    - title: Pezzi di ricambio
      url: /pezzi-di-ricambio.html
    - title: Macchinari Nuovi
      url: /macchinari-nuovi.html
    - title: Macchinari Usati
      url: /macchinari-usati.html
    - title: Contatti
      url: /contatti.html

nav_en:
    - title: "Home"
      url: /en/index.html
    - title: "The Company"
      url: /en/company.html
    - title: "Photoengraved Rollers"
      url: /en/photoengraved-rollers.html
    - title: "Rollers Catalog"
      url: /en/rollers-catalog.html
    - title: "Sanding Rolls"
      url: /en/sanding-rolls.html
    - title: "Products"
      url: javascript:void(0)
      sub-nav:
          - title: Rubbers
            url: /en/rubbers.html
          - title: Felts
            url: /en/felts.html
          - title: Buffing Carpet
            url: /en/buffing-carpet.html
          - title: Dinavac Carpet
            url: /en/dinavac-carpet.html
          - title: Lift Table
            url: /en/lift-table.html
    - title: Spare Parts
      url: /en/spare-parts.html
    - title: New Machinery
      url: /en/new.html
    - title: Second Hand Machines
      url: /en/used.html
    - title: Contacts
      url: /en/contacts.html
